#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2NhNDk3MmI4ZjEyNzdkMTdmNWNiNmY1NTI5OGExM2JjMTg4Y2Q5YzhjZDcxNzQxZGI3Zjg5ZjI3ZWNjZTBmNjg5N2UyYjI4YmJhNTgyZTg3NDcxMDk3NjNlYWU0YWM5NmY0OA==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
