apiVersion: v1
kind: Service
metadata:
  name: aodb
  namespace: aodb
  labels:
    app: aodb
spec:
  selector:
    app: aodb
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
